my_file = open("/home/mikelesnr/Documents/mypython/test.txt")
print(my_file.read())
my_file.seek(5)
print(my_file.read())

my_file.seek(0)
print(my_file.readline())
my_file.seek(0)
print(my_file.readline())
my_file.close()
